-- Every catalog food gains a default grocery-store department, the
-- Shopping List category its item auto-sorts into.  The names match the
-- Shopping List's client-minted default categories.  Users can point any
-- food (or a custom item) somewhere else; those per-user overrides live
-- in user_sort_targets and win over the catalog default.
alter table foods add column department text not null default '';

create table user_sort_targets (
    user_id    text not null references users (id) on delete cascade,
    name       text not null,
    department text not null,
    primary key (user_id, name)
);

-- Backfill the defaults for databases seeded before this migration; a
-- fresh database gets the same values from the seed itself.  Keyed by
-- name so it works on any catalog derived from the bundled one; foods
-- the catalog does not know keep the empty default and simply do not
-- auto-sort.
update foods set department = 'Condiments & Sauces' where name = 'Balsamic vinegar';
update foods set department = 'Meat & Seafood' where name = 'Sardines';
update foods set department = 'Baking & Spices' where name = 'Honey';
update foods set department = 'Condiments & Sauces' where name = 'Extra-virgin olive oil';
update foods set department = 'Condiments & Sauces' where name = 'Red wine vinegar';
update foods set department = 'Meat & Seafood' where name = 'Salmon';
update foods set department = 'Condiments & Sauces' where name = 'Red wine · optional';
update foods set department = 'Condiments & Sauces' where name = 'Olives';
update foods set department = 'Condiments & Sauces' where name = 'Apple cider vinegar';
update foods set department = 'Meat & Seafood' where name = 'Herring';
update foods set department = 'Baking & Spices' where name = 'Maple syrup';
update foods set department = 'Condiments & Sauces' where name = 'Avocado oil';
update foods set department = 'Condiments & Sauces' where name = 'Sherry vinegar';
update foods set department = 'Meat & Seafood' where name = 'Anchovies';
update foods set department = 'Baking & Spices' where name = 'Blackstrap molasses';
update foods set department = 'Condiments & Sauces' where name = 'Ghee';
update foods set department = 'Condiments & Sauces' where name = 'White wine vinegar';
update foods set department = 'Meat & Seafood' where name = 'Mackerel';
update foods set department = 'Baking & Spices' where name = 'Coconut sugar';
update foods set department = 'Condiments & Sauces' where name = 'Coconut oil';
update foods set department = 'Condiments & Sauces' where name = 'Rice vinegar';
update foods set department = 'Meat & Seafood' where name = 'Tuna';
update foods set department = 'Baking & Spices' where name = 'Jaggery';
update foods set department = 'Condiments & Sauces' where name = 'Flaxseed oil';
update foods set department = 'Condiments & Sauces' where name = 'Tomato paste';
update foods set department = 'Meat & Seafood' where name = 'Cod';
update foods set department = 'Baking & Spices' where name = 'Piloncillo';
update foods set department = 'Condiments & Sauces' where name = 'Walnut oil';
update foods set department = 'Condiments & Sauces' where name = 'Harissa';
update foods set department = 'Meat & Seafood' where name = 'Trout';
update foods set department = 'Baking & Spices' where name = 'Date syrup';
update foods set department = 'Condiments & Sauces' where name = 'Mustard oil';
update foods set department = 'Condiments & Sauces' where name = 'Pesto';
update foods set department = 'Meat & Seafood' where name = 'Sea bass';
update foods set department = 'Baking & Spices' where name = 'Agave nectar';
update foods set department = 'Condiments & Sauces' where name = 'Almond oil';
update foods set department = 'Condiments & Sauces' where name = 'Pomegranate molasses';
update foods set department = 'Meat & Seafood' where name = 'Pollock';
update foods set department = 'Baking & Spices' where name = 'Monk fruit';
update foods set department = 'Condiments & Sauces' where name = 'Perilla oil';
update foods set department = 'Condiments & Sauces' where name = 'Olive tapenade';
update foods set department = 'Canned & Dry Goods' where name = 'Tuna, canned';
update foods set department = 'Baking & Spices' where name = 'Stevia';
update foods set department = 'Condiments & Sauces' where name = 'Rapeseed oil';
update foods set department = 'Condiments & Sauces' where name = 'Anchovy paste';
update foods set department = 'Canned & Dry Goods' where name = 'Sardines, canned';
update foods set department = 'Baking & Spices' where name = 'Cacao nibs';
update foods set department = 'Condiments & Sauces' where name = 'Avocado';
update foods set department = 'Condiments & Sauces' where name = 'Hot sauce';
update foods set department = 'Canned & Dry Goods' where name = 'Salmon, canned';
update foods set department = 'Baking & Spices' where name = 'Cacao powder';
update foods set department = 'Condiments & Sauces' where name = 'Canola oil';
update foods set department = 'Canned & Dry Goods' where name = 'Lemon juice';
update foods set department = 'Meat & Seafood' where name = 'Shrimp';
update foods set department = 'Baking & Spices' where name = 'Vanilla extract';
update foods set department = 'Condiments & Sauces' where name = 'Olives, Kalamata';
update foods set department = 'Condiments & Sauces' where name = 'Fish sauce';
update foods set department = 'Meat & Seafood' where name = 'Mussels';
update foods set department = 'Condiments & Sauces' where name = 'Olives, black';
update foods set department = 'Condiments & Sauces' where name = 'Oyster sauce';
update foods set department = 'Meat & Seafood' where name = 'Clams';
update foods set department = 'Condiments & Sauces' where name = 'Olives, green';
update foods set department = 'Condiments & Sauces' where name = 'Gochujang';
update foods set department = 'Meat & Seafood' where name = 'Oysters';
update foods set department = 'Condiments & Sauces' where name = 'Sesame oil';
update foods set department = 'Condiments & Sauces' where name = 'Doubanjiang';
update foods set department = 'Meat & Seafood' where name = 'Scallops';
update foods set department = 'Condiments & Sauces' where name = 'Olive oil';
update foods set department = 'Condiments & Sauces' where name = 'Ponzu';
update foods set department = 'Meat & Seafood' where name = 'Squid';
update foods set department = 'Condiments & Sauces' where name = 'Black vinegar';
update foods set department = 'Meat & Seafood' where name = 'Octopus';
update foods set department = 'Condiments & Sauces' where name = 'Coconut aminos';
update foods set department = 'Meat & Seafood' where name = 'Crab';
update foods set department = 'Condiments & Sauces' where name = 'Salsa';
update foods set department = 'Meat & Seafood' where name = 'Halibut';
update foods set department = 'Condiments & Sauces' where name = 'Salsa verde';
update foods set department = 'Meat & Seafood' where name = 'Haddock';
update foods set department = 'Condiments & Sauces' where name = 'Chipotle in adobo';
update foods set department = 'Meat & Seafood' where name = 'Arctic char';
update foods set department = 'Condiments & Sauces' where name = 'Tamarind paste';
update foods set department = 'Meat & Seafood' where name = 'Snapper';
update foods set department = 'Condiments & Sauces' where name = 'Mango chutney';
update foods set department = 'Meat & Seafood' where name = 'Tilapia';
update foods set department = 'Condiments & Sauces' where name = 'Sambal oelek';
update foods set department = 'Meat & Seafood' where name = 'Barramundi';
update foods set department = 'Canned & Dry Goods' where name = 'Bone broth';
update foods set department = 'Meat & Seafood' where name = 'Rockfish';
update foods set department = 'Canned & Dry Goods' where name = 'Vegetable broth';
update foods set department = 'Canned & Dry Goods' where name = 'Mackerel, canned';
update foods set department = 'Condiments & Sauces' where name = 'Mustard, Dijon';
update foods set department = 'Meat & Seafood' where name = 'Salmon, smoked';
update foods set department = 'Condiments & Sauces' where name = 'Mustard, brown';
update foods set department = 'Meat & Seafood' where name = 'Mackerel, smoked';
update foods set department = 'Condiments & Sauces' where name = 'Chili paste';
update foods set department = 'Meat & Seafood' where name = 'Lobster';
update foods set department = 'Condiments & Sauces' where name = 'Salsa roja';
update foods set department = 'Meat & Seafood' where name = 'Roe';
update foods set department = 'Canned & Dry Goods' where name = 'Vegetable stock';
update foods set department = 'Canned & Dry Goods' where name = 'Herring, canned';
update foods set department = 'Condiments & Sauces' where name = 'Garlic paste';
update foods set department = 'Condiments & Sauces' where name = 'Chili sauce';
update foods set department = 'Canned & Dry Goods' where name = 'Chicken broth';
update foods set department = 'Condiments & Sauces' where name = 'Curry paste, red';
update foods set department = 'Canned & Dry Goods' where name = 'Lentils';
update foods set department = 'Dairy' where name = 'Eggs';
update foods set department = 'Canned & Dry Goods' where name = 'Red meat';
update foods set department = 'Produce' where name = 'Spinach';
update foods set department = 'Canned & Dry Goods' where name = 'Chickpeas';
update foods set department = 'Meat & Seafood' where name = 'Duck';
update foods set department = 'Canned & Dry Goods' where name = 'Rich cheeses';
update foods set department = 'Produce' where name = 'Kale';
update foods set department = 'Canned & Dry Goods' where name = 'White beans';
update foods set department = 'Meat & Seafood' where name = 'Quail';
update foods set department = 'Canned & Dry Goods' where name = 'Sweets & pastries';
update foods set department = 'Produce' where name = 'Swiss chard';
update foods set department = 'Canned & Dry Goods' where name = 'Fava beans';
update foods set department = 'Meat & Seafood' where name = 'Duck eggs';
update foods set department = 'Canned & Dry Goods' where name = 'Dark chocolate';
update foods set department = 'Produce' where name = 'Arugula';
update foods set department = 'Canned & Dry Goods' where name = 'Black-eyed peas';
update foods set department = 'Meat & Seafood' where name = 'Quail eggs';
update foods set department = 'Canned & Dry Goods' where name = 'Roasted chickpeas';
update foods set department = 'Produce' where name = 'Romaine';
update foods set department = 'Canned & Dry Goods' where name = 'Split peas';
update foods set department = 'Meat & Seafood' where name = 'Chicken, breast';
update foods set department = 'Canned & Dry Goods' where name = 'Roasted edamame';
update foods set department = 'Produce' where name = 'Dandelion greens';
update foods set department = 'Canned & Dry Goods' where name = 'Kidney beans';
update foods set department = 'Meat & Seafood' where name = 'Chicken, thigh';
update foods set department = 'Canned & Dry Goods' where name = 'Seaweed snacks';
update foods set department = 'Produce' where name = 'Watercress';
update foods set department = 'Canned & Dry Goods' where name = 'Butter beans';
update foods set department = 'Meat & Seafood' where name = 'Chicken, whole';
update foods set department = 'Canned & Dry Goods' where name = 'Roasted makhana';
update foods set department = 'Produce' where name = 'Collard greens';
update foods set department = 'Canned & Dry Goods' where name = 'Borlotti beans';
update foods set department = 'Meat & Seafood' where name = 'Turkey, thigh';
update foods set department = 'Canned & Dry Goods' where name = 'Kale chips';
update foods set department = 'Produce' where name = 'Beet greens';
update foods set department = 'Canned & Dry Goods' where name = 'Lupini beans';
update foods set department = 'Meat & Seafood' where name = 'Turkey, breast';
update foods set department = 'Canned & Dry Goods' where name = 'Whole-grain crackers';
update foods set department = 'Produce' where name = 'Endive';
update foods set department = 'Canned & Dry Goods' where name = 'Green peas';
update foods set department = 'Meat & Seafood' where name = 'Turkey, leg';
update foods set department = 'Canned & Dry Goods' where name = 'Rye crisps';
update foods set department = 'Produce' where name = 'Radicchio';
update foods set department = 'Canned & Dry Goods' where name = 'Cannellini beans';
update foods set department = 'Meat & Seafood' where name = 'Chicken, leg';
update foods set department = 'Canned & Dry Goods' where name = 'Air-popped popcorn';
update foods set department = 'Produce' where name = 'Escarole';
update foods set department = 'Canned & Dry Goods' where name = 'Pinto beans';
update foods set department = 'Meat & Seafood' where name = 'Chicken, wing';
update foods set department = 'Canned & Dry Goods' where name = 'Plantain chips';
update foods set department = 'Produce' where name = 'Mustard greens';
update foods set department = 'Canned & Dry Goods' where name = 'Edamame';
update foods set department = 'Meat & Seafood' where name = 'Turkey, ground';
update foods set department = 'Canned & Dry Goods' where name = 'Trail mix';
update foods set department = 'Produce' where name = 'Bok choy';
update foods set department = 'Canned & Dry Goods' where name = 'Hummus';
update foods set department = 'Canned & Dry Goods' where name = 'Nut & seed bars';
update foods set department = 'Produce' where name = 'Turnip greens';
update foods set department = 'Canned & Dry Goods' where name = 'Adzuki beans';
update foods set department = 'Bulk' where name = 'Dried mango';
update foods set department = 'Produce' where name = 'Frisée';
update foods set department = 'Canned & Dry Goods' where name = 'Mung beans';
update foods set department = 'Meat & Seafood' where name = 'Turkey jerky';
update foods set department = 'Produce' where name = 'Purslane';
update foods set department = 'Canned & Dry Goods' where name = 'Soybeans';
update foods set department = 'Meat & Seafood' where name = 'Beef jerky';
update foods set department = 'Produce' where name = 'Mizuna';
update foods set department = 'Canned & Dry Goods' where name = 'Red beans';
update foods set department = 'Canned & Dry Goods' where name = 'Whole-grain pretzels';
update foods set department = 'Produce' where name = 'Komatsuna';
update foods set department = 'Canned & Dry Goods' where name = 'Black beans';
update foods set department = 'Canned & Dry Goods' where name = 'Rice cakes';
update foods set department = 'Produce' where name = 'Chrysanthemum greens';
update foods set department = 'Canned & Dry Goods' where name = 'Pigeon peas';
update foods set department = 'Canned & Dry Goods' where name = 'Oatcakes';
update foods set department = 'Produce' where name = 'Tatsoi';
update foods set department = 'Canned & Dry Goods' where name = 'Black gram';
update foods set department = 'Canned & Dry Goods' where name = 'Falafel';
update foods set department = 'Produce' where name = 'Shiso';
update foods set department = 'Canned & Dry Goods' where name = 'Black chickpeas';
update foods set department = 'Canned & Dry Goods' where name = 'Roasted chana';
update foods set department = 'Produce' where name = 'Chinese broccoli';
update foods set department = 'Canned & Dry Goods' where name = 'Navy beans';
update foods set department = 'Canned & Dry Goods' where name = 'Puffed rice';
update foods set department = 'Produce' where name = 'Choy sum';
update foods set department = 'Canned & Dry Goods' where name = 'Great northern beans';
update foods set department = 'Canned & Dry Goods' where name = 'Banana chips';
update foods set department = 'Produce' where name = 'Water spinach';
update foods set department = 'Canned & Dry Goods' where name = 'Cranberry beans';
update foods set department = 'Canned & Dry Goods' where name = 'Coconut chips';
update foods set department = 'Produce' where name = 'Amaranth greens';
update foods set department = 'Canned & Dry Goods' where name = 'Peanuts';
update foods set department = 'Canned & Dry Goods' where name = 'Granola';
update foods set department = 'Produce' where name = 'Fenugreek leaves';
update foods set department = 'Canned & Dry Goods' where name = 'Moth beans';
update foods set department = 'Canned & Dry Goods' where name = 'Energy balls';
update foods set department = 'Produce' where name = 'Moringa leaves';
update foods set department = 'Canned & Dry Goods' where name = 'Horse gram';
update foods set department = 'Canned & Dry Goods' where name = 'Salami';
update foods set department = 'Produce' where name = 'Pea shoots';
update foods set department = 'Canned & Dry Goods' where name = 'Black beans, canned';
update foods set department = 'Produce' where name = 'Sorrel';
update foods set department = 'Canned & Dry Goods' where name = 'Cannellini beans, canned';
update foods set department = 'Produce' where name = 'Mâche';
update foods set department = 'Baking & Spices' where name = 'Chickpea flour';
update foods set department = 'Produce' where name = 'Nettles';
update foods set department = 'Canned & Dry Goods' where name = 'Red beans, canned';
update foods set department = 'Produce' where name = 'Cilantro';
update foods set department = 'Canned & Dry Goods' where name = 'Chickpeas, canned';
update foods set department = 'Produce' where name = 'Parsley';
update foods set department = 'Canned & Dry Goods' where name = 'Kidney beans, canned';
update foods set department = 'Produce' where name = 'Radish greens';
update foods set department = 'Canned & Dry Goods' where name = 'Great northern beans, canned';
update foods set department = 'Produce' where name = 'Carrot greens';
update foods set department = 'Canned & Dry Goods' where name = 'White beans, canned';
update foods set department = 'Produce' where name = 'Parsley, Italian';
update foods set department = 'Canned & Dry Goods' where name = 'Navy beans, canned';
update foods set department = 'Produce' where name = 'Parsley, curly';
update foods set department = 'Canned & Dry Goods' where name = 'Pinto beans, canned';
update foods set department = 'Produce' where name = 'Pea greens';
update foods set department = 'Canned & Dry Goods' where name = 'Peas';
update foods set department = 'Produce' where name = 'Sprouts, mustard';
update foods set department = 'Canned & Dry Goods' where name = 'Peas, canned/frozen';
update foods set department = 'Produce' where name = 'Sprouts, broccoli';
update foods set department = 'Canned & Dry Goods' where name = 'Lentils, red';
update foods set department = 'Produce' where name = 'Sprouts';
update foods set department = 'Canned & Dry Goods' where name = 'Lentils, green';
update foods set department = 'Produce' where name = 'Sprouts, bean';
update foods set department = 'Canned & Dry Goods' where name = 'Lentils, brown';
update foods set department = 'Produce' where name = 'Spinach, Malabar';
update foods set department = 'Canned & Dry Goods' where name = 'Lentils, black';
update foods set department = 'Produce' where name = 'Sprouts, alfalfa';
update foods set department = 'Bulk' where name = 'Walnuts';
update foods set department = 'Produce' where name = 'Eggplant';
update foods set department = 'Bulk' where name = 'Almonds';
update foods set department = 'Produce' where name = 'Zucchini';
update foods set department = 'Bulk' where name = 'Pistachios';
update foods set department = 'Produce' where name = 'Broccoli';
update foods set department = 'Bulk' where name = 'Hazelnuts';
update foods set department = 'Produce' where name = 'Cauliflower';
update foods set department = 'Bulk' where name = 'Pine nuts';
update foods set department = 'Produce' where name = 'Fennel';
update foods set department = 'Bulk' where name = 'Tahini';
update foods set department = 'Produce' where name = 'Cucumber';
update foods set department = 'Bulk' where name = 'Sunflower seeds';
update foods set department = 'Produce' where name = 'Asparagus';
update foods set department = 'Bulk' where name = 'Pumpkin seeds';
update foods set department = 'Produce' where name = 'Leeks';
update foods set department = 'Bulk' where name = 'Chia seeds';
update foods set department = 'Produce' where name = 'Celery';
update foods set department = 'Bulk' where name = 'Cashews';
update foods set department = 'Produce' where name = 'Beets';
update foods set department = 'Bulk' where name = 'Pecans';
update foods set department = 'Produce' where name = 'Cabbage';
update foods set department = 'Bulk' where name = 'Sesame seeds';
update foods set department = 'Produce' where name = 'Brussels sprouts';
update foods set department = 'Bulk' where name = 'Brazil nuts';
update foods set department = 'Produce' where name = 'Okra';
update foods set department = 'Bulk' where name = 'Macadamia nuts';
update foods set department = 'Produce' where name = 'Capers';
update foods set department = 'Bulk' where name = 'Almond butter';
update foods set department = 'Bulk' where name = 'Tomatoes, sun-dried';
update foods set department = 'Bulk' where name = 'Hemp seeds';
update foods set department = 'Produce' where name = 'Sweet potato';
update foods set department = 'Bulk' where name = 'Pepitas';
update foods set department = 'Produce' where name = 'Butternut squash';
update foods set department = 'Bulk' where name = 'Peanut butter';
update foods set department = 'Produce' where name = 'Green beans';
update foods set department = 'Bulk' where name = 'Cashew butter';
update foods set department = 'Produce' where name = 'Turnips';
update foods set department = 'Bulk' where name = 'Poppy seeds';
update foods set department = 'Produce' where name = 'Kohlrabi';
update foods set department = 'Bulk' where name = 'Watermelon seeds';
update foods set department = 'Produce' where name = 'Chili peppers';
update foods set department = 'Bulk' where name = 'Lotus seeds';
update foods set department = 'Produce' where name = 'Shiitake';
update foods set department = 'Canned & Dry Goods' where name = 'Coconut milk';
update foods set department = 'Produce' where name = 'Maitake';
update foods set department = 'Baking & Spices' where name = 'Almond flour';
update foods set department = 'Produce' where name = 'Enoki';
update foods set department = 'Canned & Dry Goods' where name = 'Almond milk';
update foods set department = 'Produce' where name = 'Daikon';
update foods set department = 'Bulk' where name = 'Coconut, shredded';
update foods set department = 'Produce' where name = 'Burdock root';
update foods set department = 'Bulk' where name = 'Coconut, baby';
update foods set department = 'Produce' where name = 'Lotus root';
update foods set department = 'Bulk' where name = 'Almonds, slivered';
update foods set department = 'Produce' where name = 'Bitter melon';
update foods set department = 'Bulk' where name = 'Flaxseed, ground';
update foods set department = 'Produce' where name = 'Napa cabbage';
update foods set department = 'Bulk' where name = 'Flaxseed, whole';
update foods set department = 'Produce' where name = 'Bamboo shoots';
update foods set department = 'Produce' where name = 'Parsnip';
update foods set department = 'Produce' where name = 'Rutabaga';
update foods set department = 'Produce' where name = 'Shallots';
update foods set department = 'Produce' where name = 'Romanesco';
update foods set department = 'Produce' where name = 'Broccolini';
update foods set department = 'Produce' where name = 'Broccoli rabe';
update foods set department = 'Produce' where name = 'Sunchokes';
update foods set department = 'Produce' where name = 'Celeriac';
update foods set department = 'Produce' where name = 'Kabocha squash';
update foods set department = 'Produce' where name = 'Delicata squash';
update foods set department = 'Produce' where name = 'Acorn squash';
update foods set department = 'Produce' where name = 'Spaghetti squash';
update foods set department = 'Produce' where name = 'Heirloom tomatoes';
update foods set department = 'Produce' where name = 'Watermelon radish';
update foods set department = 'Produce' where name = 'Snap peas';
update foods set department = 'Produce' where name = 'Snow peas';
update foods set department = 'Produce' where name = 'Broccoli sprouts';
update foods set department = 'Produce' where name = 'Alfalfa sprouts';
update foods set department = 'Produce' where name = 'Microgreens';
update foods set department = 'Produce' where name = 'Chayote';
update foods set department = 'Produce' where name = 'Water chestnuts';
update foods set department = 'Produce' where name = 'Horseradish';
update foods set department = 'Produce' where name = 'Tomatillos';
update foods set department = 'Produce' where name = 'Nopales';
update foods set department = 'Produce' where name = 'Jicama';
update foods set department = 'Produce' where name = 'Serrano peppers';
update foods set department = 'Produce' where name = 'Sweet corn';
update foods set department = 'Produce' where name = 'Taro';
update foods set department = 'Produce' where name = 'Yam';
update foods set department = 'Produce' where name = 'Winter melon';
update foods set department = 'Produce' where name = 'Long beans';
update foods set department = 'Produce' where name = 'Bottle gourd';
update foods set department = 'Produce' where name = 'Ridge gourd';
update foods set department = 'Produce' where name = 'Drumsticks';
update foods set department = 'Produce' where name = 'Cluster beans';
update foods set department = 'Produce' where name = 'Shishito peppers';
update foods set department = 'Produce' where name = 'Garlic scapes';
update foods set department = 'Produce' where name = 'Fiddleheads';
update foods set department = 'Produce' where name = 'Ramps';
update foods set department = 'Produce' where name = 'Chinese celery';
update foods set department = 'Produce' where name = 'Baby corn';
update foods set department = 'Produce' where name = 'Ivy gourd';
update foods set department = 'Produce' where name = 'Cassava';
update foods set department = 'Produce' where name = 'Wakame';
update foods set department = 'Produce' where name = 'Nori';
update foods set department = 'Produce' where name = 'Artichoke hearts';
update foods set department = 'Bulk' where name = 'Shiitake, dried';
update foods set department = 'Canned & Dry Goods' where name = 'Tomatoes, canned, diced';
update foods set department = 'Canned & Dry Goods' where name = 'Tomatoes, canned, crushed';
update foods set department = 'Produce' where name = 'Tomato sauce, jar/can';
update foods set department = 'Produce' where name = 'Bell pepper, green';
update foods set department = 'Produce' where name = 'Bell pepper, red';
update foods set department = 'Produce' where name = 'Bell pepper, yellow';
update foods set department = 'Produce' where name = 'Artichoke';
update foods set department = 'Produce' where name = 'Onions, green';
update foods set department = 'Produce' where name = 'Onion, sweet';
update foods set department = 'Produce' where name = 'Onion, yellow';
update foods set department = 'Produce' where name = 'Onion, red';
update foods set department = 'Produce' where name = 'Onion, white';
update foods set department = 'Produce' where name = 'Potatoes, red';
update foods set department = 'Produce' where name = 'Potatoes, Russet';
update foods set department = 'Produce' where name = 'Potatoes, Yukon';
update foods set department = 'Produce' where name = 'Tomatoes, cherry';
update foods set department = 'Produce' where name = 'Tomatoes, roma';
update foods set department = 'Produce' where name = 'Tomatoes, heirloom';
update foods set department = 'Produce' where name = 'Tomato';
update foods set department = 'Produce' where name = 'Garlic clove';
update foods set department = 'Produce' where name = 'Carrot';
update foods set department = 'Produce' where name = 'Anaheim pepper';
update foods set department = 'Produce' where name = 'Poblano pepper';
update foods set department = 'Produce' where name = 'Roasted red peppers';
update foods set department = 'Produce' where name = 'Habanero peppers';
update foods set department = 'Produce' where name = 'Mushrooms, shiitake';
update foods set department = 'Produce' where name = 'Mushrooms, white';
update foods set department = 'Produce' where name = 'Mushroom, portobello';
update foods set department = 'Produce' where name = 'Mushrooms, cremini';
update foods set department = 'Produce' where name = 'Mushrooms, oyster';
update foods set department = 'Produce' where name = 'Mushrooms, trumpet';
update foods set department = 'Produce' where name = 'Mushrooms, enoki';
update foods set department = 'Produce' where name = 'Eggplant, Chinese';
update foods set department = 'Produce' where name = 'Eggplant, Indian';
update foods set department = 'Produce' where name = 'Jalapeno';
update foods set department = 'Produce' where name = 'Radish';
update foods set department = 'Canned & Dry Goods' where name = 'Oats';
update foods set department = 'Produce' where name = 'Tofu';
update foods set department = 'Canned & Dry Goods' where name = 'Farro';
update foods set department = 'Produce' where name = 'Natto';
update foods set department = 'Canned & Dry Goods' where name = 'Barley';
update foods set department = 'Produce' where name = 'Miso';
update foods set department = 'Canned & Dry Goods' where name = 'Bulgur';
update foods set department = 'Produce' where name = 'Tempeh';
update foods set department = 'Canned & Dry Goods' where name = 'Quinoa';
update foods set department = 'Produce' where name = 'Tamari / soy sauce';
update foods set department = 'Bakery' where name = 'Whole-grain bread';
update foods set department = 'Produce' where name = 'Kimchi';
update foods set department = 'Canned & Dry Goods' where name = 'Whole-wheat pasta';
update foods set department = 'Produce' where name = 'Sauerkraut';
update foods set department = 'Canned & Dry Goods' where name = 'Buckwheat / soba';
update foods set department = 'Produce' where name = 'Pickled vegetables';
update foods set department = 'Canned & Dry Goods' where name = 'Millet';
update foods set department = 'Produce' where name = 'Doenjang';
update foods set department = 'Canned & Dry Goods' where name = 'Rye';
update foods set department = 'Produce' where name = 'Fermented black beans';
update foods set department = 'Canned & Dry Goods' where name = 'Freekeh';
update foods set department = 'Produce' where name = 'Fermented tofu';
update foods set department = 'Canned & Dry Goods' where name = 'Sorghum';
update foods set department = 'Canned & Dry Goods' where name = 'Soy milk';
update foods set department = 'Canned & Dry Goods' where name = 'Amaranth';
update foods set department = 'Baking & Spices' where name = 'Nutritional yeast';
update foods set department = 'Canned & Dry Goods' where name = 'Teff';
update foods set department = 'Canned & Dry Goods' where name = 'Spelt';
update foods set department = 'Canned & Dry Goods' where name = 'Kamut';
update foods set department = 'Canned & Dry Goods' where name = 'Fonio';
update foods set department = 'Canned & Dry Goods' where name = 'Finger millet';
update foods set department = 'Canned & Dry Goods' where name = 'Pearl millet';
update foods set department = 'Canned & Dry Goods' where name = 'Job''s tears';
update foods set department = 'Bakery' where name = 'Whole-grain corn tortillas';
update foods set department = 'Canned & Dry Goods' where name = 'Brown rice noodles';
update foods set department = 'Canned & Dry Goods' where name = 'Whole-wheat couscous';
update foods set department = 'Bakery' where name = 'Whole-wheat pita';
update foods set department = 'Baking & Spices' where name = 'Rye flour';
update foods set department = 'Baking & Spices' where name = 'Whole-wheat flour';
update foods set department = 'Baking & Spices' where name = 'Buckwheat flour';
update foods set department = 'Baking & Spices' where name = 'Oat flour';
update foods set department = 'Baking & Spices' where name = 'Cornmeal';
update foods set department = 'Canned & Dry Goods' where name = 'Oat milk';
update foods set department = 'Baking & Spices' where name = 'Brown rice flour';
update foods set department = 'Canned & Dry Goods' where name = 'Rice, wild';
update foods set department = 'Canned & Dry Goods' where name = 'Rice, red';
update foods set department = 'Canned & Dry Goods' where name = 'Rice, brown';
update foods set department = 'Canned & Dry Goods' where name = 'Rice, black';
update foods set department = 'Bakery' where name = 'Sprouted-grain bread';
update foods set department = 'Baking & Spices' where name = 'White flour';
update foods set department = 'Produce' where name = 'Berries';
update foods set department = 'Dairy' where name = 'Kefir';
update foods set department = 'Produce' where name = 'Pomegranate';
update foods set department = 'Dairy' where name = 'Skyr';
update foods set department = 'Produce' where name = 'Figs';
update foods set department = 'Dairy' where name = 'Feta';
update foods set department = 'Produce' where name = 'Grapes';
update foods set department = 'Dairy' where name = 'Pecorino / Parmesan';
update foods set department = 'Produce' where name = 'Oranges';
update foods set department = 'Dairy' where name = 'Ricotta';
update foods set department = 'Produce' where name = 'Apples';
update foods set department = 'Dairy' where name = 'Paneer';
update foods set department = 'Produce' where name = 'Pears';
update foods set department = 'Dairy' where name = 'Buttermilk';
update foods set department = 'Produce' where name = 'Melon';
update foods set department = 'Dairy' where name = 'Queso fresco';
update foods set department = 'Produce' where name = 'Dates';
update foods set department = 'Dairy' where name = 'Cotija';
update foods set department = 'Produce' where name = 'Apricots';
update foods set department = 'Dairy' where name = 'Cottage cheese';
update foods set department = 'Produce' where name = 'Peaches';
update foods set department = 'Dairy' where name = 'Labneh';
update foods set department = 'Produce' where name = 'Plums';
update foods set department = 'Dairy' where name = 'Manchego';
update foods set department = 'Produce' where name = 'Cherries';
update foods set department = 'Dairy' where name = 'Halloumi';
update foods set department = 'Produce' where name = 'Grapefruit';
update foods set department = 'Dairy' where name = 'Mozzarella';
update foods set department = 'Produce' where name = 'Nectarines';
update foods set department = 'Dairy' where name = 'Cheese, goat';
update foods set department = 'Produce' where name = 'Kiwi';
update foods set department = 'Dairy' where name = 'Yogurt, Greek';
update foods set department = 'Produce' where name = 'Persimmon';
update foods set department = 'Dairy' where name = 'Yogurt, skyr';
update foods set department = 'Produce' where name = 'Quince';
update foods set department = 'Produce' where name = 'Prunes';
update foods set department = 'Produce' where name = 'Raisins';
update foods set department = 'Produce' where name = 'Mandarins';
update foods set department = 'Produce' where name = 'Asian pear';
update foods set department = 'Produce' where name = 'Lingonberries';
update foods set department = 'Produce' where name = 'Bilberries';
update foods set department = 'Produce' where name = 'Black currants';
update foods set department = 'Produce' where name = 'Sea buckthorn';
update foods set department = 'Produce' where name = 'Yuzu';
update foods set department = 'Produce' where name = 'Mango';
update foods set department = 'Produce' where name = 'Papaya';
update foods set department = 'Produce' where name = 'Guava';
update foods set department = 'Produce' where name = 'Pineapple';
update foods set department = 'Produce' where name = 'Passion fruit';
update foods set department = 'Produce' where name = 'Dragon fruit';
update foods set department = 'Produce' where name = 'Lychee';
update foods set department = 'Produce' where name = 'Longan';
update foods set department = 'Produce' where name = 'Rambutan';
update foods set department = 'Produce' where name = 'Mangosteen';
update foods set department = 'Produce' where name = 'Jackfruit';
update foods set department = 'Produce' where name = 'Pomelo';
update foods set department = 'Produce' where name = 'Loquat';
update foods set department = 'Produce' where name = 'Cherimoya';
update foods set department = 'Produce' where name = 'Prickly pear';
update foods set department = 'Produce' where name = 'Tamarind';
update foods set department = 'Produce' where name = 'Indian gooseberry';
update foods set department = 'Produce' where name = 'Sapota';
update foods set department = 'Produce' where name = 'Jamun';
update foods set department = 'Produce' where name = 'Blackberries';
update foods set department = 'Produce' where name = 'Raspberries';
update foods set department = 'Produce' where name = 'Strawberries';
update foods set department = 'Produce' where name = 'Blueberries';
update foods set department = 'Produce' where name = 'Cranberries';
update foods set department = 'Produce' where name = 'Gooseberries';
update foods set department = 'Produce' where name = 'Mulberries';
update foods set department = 'Produce' where name = 'Elderberries';
update foods set department = 'Produce' where name = 'Aronia berries';
update foods set department = 'Produce' where name = 'Goji berries';
update foods set department = 'Produce' where name = 'Banana';
update foods set department = 'Produce' where name = 'Cantaloupe';
update foods set department = 'Produce' where name = 'Watermelon';
update foods set department = 'Produce' where name = 'Starfruit';
update foods set department = 'Produce' where name = 'Tart cherries';
update foods set department = 'Produce' where name = 'Açaí';
update foods set department = 'Produce' where name = 'Camu camu';
update foods set department = 'Produce' where name = 'Limes';
update foods set department = 'Bulk' where name = 'Figs, dried';
update foods set department = 'Bulk' where name = 'Apricots, dried';
update foods set department = 'Bulk' where name = 'Cranberries, dried';
update foods set department = 'Produce' where name = 'Applesauce';
update foods set department = 'Produce' where name = 'Plantain';
update foods set department = 'Canned & Dry Goods' where name = 'Cranberry juice';
update foods set department = 'Baking & Spices' where name = 'Turmeric';
update foods set department = 'Health & Wellness' where name = 'Omega-3 fish oil';
update foods set department = 'Produce' where name = 'Basil';
update foods set department = 'Health & Wellness' where name = 'Curcumin';
update foods set department = 'Baking & Spices' where name = 'Oregano';
update foods set department = 'Health & Wellness' where name = 'Vitamin D';
update foods set department = 'Produce' where name = 'Rosemary';
update foods set department = 'Health & Wellness' where name = 'Ginger extract';
update foods set department = 'Produce' where name = 'Mint';
update foods set department = 'Health & Wellness' where name = 'Boswellia';
update foods set department = 'Produce' where name = 'Thyme';
update foods set department = 'Health & Wellness' where name = 'Resveratrol';
update foods set department = 'Baking & Spices' where name = 'Cinnamon';
update foods set department = 'Health & Wellness' where name = 'Probiotics';
update foods set department = 'Baking & Spices' where name = 'Black pepper';
update foods set department = 'Health & Wellness' where name = 'Spirulina';
update foods set department = 'Baking & Spices' where name = 'Sumac';
update foods set department = 'Health & Wellness' where name = 'Chlorella';
update foods set department = 'Baking & Spices' where name = 'Wasabi';
update foods set department = 'Health & Wellness' where name = 'Ashwagandha';
update foods set department = 'Baking & Spices' where name = 'Caraway';
update foods set department = 'Health & Wellness' where name = 'Acai powder';
update foods set department = 'Baking & Spices' where name = 'Star anise';
update foods set department = 'Health & Wellness' where name = 'Blueberry powder';
update foods set department = 'Baking & Spices' where name = 'Cardamom';
update foods set department = 'Health & Wellness' where name = 'Creatine powder';
update foods set department = 'Baking & Spices' where name = 'Cloves';
update foods set department = 'Health & Wellness' where name = 'Theobromine powder';
update foods set department = 'Produce' where name = 'Sage';
update foods set department = 'Health & Wellness' where name = 'Beet powder';
update foods set department = 'Baking & Spices' where name = 'Cumin';
update foods set department = 'Health & Wellness' where name = 'Multivitamin';
update foods set department = 'Baking & Spices' where name = 'Coriander seeds';
update foods set department = 'Health & Wellness' where name = 'Garlic extract';
update foods set department = 'Baking & Spices' where name = 'Mustard seeds';
update foods set department = 'Health & Wellness' where name = 'Vitamin B12';
update foods set department = 'Baking & Spices' where name = 'Fenugreek seeds';
update foods set department = 'Health & Wellness' where name = 'Cranberry powder';
update foods set department = 'Baking & Spices' where name = 'Fennel seeds';
update foods set department = 'Health & Wellness' where name = 'Green tea extract';
update foods set department = 'Produce' where name = 'Curry leaves';
update foods set department = 'Baking & Spices' where name = 'Garam masala';
update foods set department = 'Baking & Spices' where name = 'Asafoetida';
update foods set department = 'Baking & Spices' where name = 'Nigella seeds';
update foods set department = 'Baking & Spices' where name = 'Ajwain';
update foods set department = 'Baking & Spices' where name = 'Saffron';
update foods set department = 'Baking & Spices' where name = 'Bay leaves';
update foods set department = 'Baking & Spices' where name = 'Allspice';
update foods set department = 'Baking & Spices' where name = 'Mexican oregano';
update foods set department = 'Baking & Spices' where name = 'Epazote';
update foods set department = 'Baking & Spices' where name = 'Annatto';
update foods set department = 'Baking & Spices' where name = 'Sichuan peppercorns';
update foods set department = 'Produce' where name = 'Lemongrass';
update foods set department = 'Baking & Spices' where name = 'Galangal';
update foods set department = 'Produce' where name = 'Kaffir lime leaves';
update foods set department = 'Produce' where name = 'Thai basil';
update foods set department = 'Produce' where name = 'Tarragon';
update foods set department = 'Baking & Spices' where name = 'Marjoram';
update foods set department = 'Baking & Spices' where name = 'Za''atar';
update foods set department = 'Baking & Spices' where name = 'Gochugaru';
update foods set department = 'Baking & Spices' where name = 'Chinese five-spice';
update foods set department = 'Baking & Spices' where name = 'Cayenne';
update foods set department = 'Baking & Spices' where name = 'Ginger, ground';
update foods set department = 'Baking & Spices' where name = 'Garlic powder';
update foods set department = 'Baking & Spices' where name = 'Paprika';
update foods set department = 'Baking & Spices' where name = 'Paprika, smoked';
update foods set department = 'Baking & Spices' where name = 'Chives, dried';
update foods set department = 'Produce' where name = 'Chives';
update foods set department = 'Baking & Spices' where name = 'Parsley, dried';
update foods set department = 'Produce' where name = 'Dill';
update foods set department = 'Produce' where name = 'Ginger, fresh';
update foods set department = 'Baking & Spices' where name = 'Chili powder';
update foods set department = 'Baking & Spices' where name = 'Coriander';
update foods set department = 'Baking & Spices' where name = 'Onion powder';
update foods set department = 'Baking & Spices' where name = 'Salt';
update foods set department = 'Baking & Spices' where name = 'Lemon';
update foods set department = 'Baking & Spices' where name = 'Curry powder';
update foods set department = 'Coffee & Tea' where name = 'Green tea';
update foods set department = 'Coffee & Tea' where name = 'Matcha';
update foods set department = 'Coffee & Tea' where name = 'Sencha';
update foods set department = 'Coffee & Tea' where name = 'Hojicha';
update foods set department = 'Coffee & Tea' where name = 'Hibiscus';
update foods set department = 'Coffee & Tea' where name = 'Oolong tea';
update foods set department = 'Coffee & Tea' where name = 'Pu-erh tea';
update foods set department = 'Coffee & Tea' where name = 'White tea';
update foods set department = 'Coffee & Tea' where name = 'Jasmine tea';
update foods set department = 'Coffee & Tea' where name = 'Genmaicha';
update foods set department = 'Coffee & Tea' where name = 'Gyokuro';
update foods set department = 'Coffee & Tea' where name = 'Barley tea';
update foods set department = 'Coffee & Tea' where name = 'Chrysanthemum tea';
update foods set department = 'Coffee & Tea' where name = 'Rooibos';
update foods set department = 'Coffee & Tea' where name = 'Yerba mate';
update foods set department = 'Coffee & Tea' where name = 'Tulsi';
update foods set department = 'Coffee & Tea' where name = 'Chamomile';
update foods set department = 'Coffee & Tea' where name = 'Peppermint tea';
update foods set department = 'Coffee & Tea' where name = 'Ginger tea';
update foods set department = 'Coffee & Tea' where name = 'Kombucha';
update foods set department = 'Coffee & Tea' where name = 'Wheatgrass';
update foods set department = 'Coffee & Tea' where name = 'Coffee';
