# Crane-based derivation for the food4u-server binary.
# Called from flake.nix with: import ./server.nix { inherit craneLib commonArgs pkgs; }
#
# The package output is a single self-contained binary:
#   $out/bin/food4u-server — the server, with the compiled Elm frontend
#                            embedded into it.
#
# The frontend is built by the `elmFrontend` derivation below and handed to
# the crate build through the `RUST_TEMPLATE_FRONTEND_DIR` environment
# variable, which the server crate's `build.rs` forwards to the `rust_embed`
# `Frontend` type.  Embedding (rather than shipping a sibling asset
# directory) means a downloaded release binary needs nothing alongside it —
# there is no `--frontend-path` to point at a separate directory.
#
# Elm build: uses pkgs.elmPackages.fetchElmDeps with the elm-srcs.nix and
# registry.dat files generated by elm2nix.  All package fetching happens
# through individual fixed-output derivations, so the build is fully offline
# and hermetic.
#
# When elm.json dependency versions change, regenerate both files:
#   cd frontend
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- convert 2>/dev/null > elm-srcs.nix
#   nix run 'github:NixOS/nixpkgs/25.11#elm2nix' -- snapshot
# then commit elm-srcs.nix and registry.dat.
{
  craneLib,
  commonArgs,
  pkgs,
}: let
  elmFrontend = pkgs.stdenv.mkDerivation {
    name = "food4u-elm-frontend";
    src = ../../frontend;
    nativeBuildInputs = [
      pkgs.elmPackages.elm
      # Minifies the --optimize'd Elm output in buildPhase, kept in sync
      # with the dev shell so the packaged and local bundles are identical.
      pkgs.nodePackages.terser
    ];

    configurePhase = pkgs.elmPackages.fetchElmDeps {
      elmPackages = import ../../frontend/elm-srcs.nix;
      elmVersion = "0.19.1";
      registryDat = ../../frontend/registry.dat;
    };

    # Compile with --optimize, then minify with Elm's recommended two-pass
    # terser invocation: a compress pass that treats the generated wrapper
    # helpers (F2..F9, A2..A9) as pure so dead code folds away, followed by
    # a mangle pass.  The optimized-but-unminified intermediate is not kept.
    buildPhase = ''
      elm make src/Main.elm --optimize --output elm.unminified.js
      terser elm.unminified.js \
        --compress 'pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe' \
        | terser --mangle --output elm.js
    '';

    installPhase = ''
      mkdir -p $out
      cp elm.js $out/
      cp public/style.css $out/
      cp public/about.html $out/
      # Stamp the script src with the Nix store hash so each build gets a
      # unique URL.  Browsers that cached /elm.js from a previous build will
      # fetch the new /elm.js?v=<hash> URL instead.
      STORE_HASH=$(basename $out | cut -d'-' -f1)
      sed "s|/elm.js|/elm.js?v=$STORE_HASH|g" public/index.html > $out/index.html
    '';
  };
in
  craneLib.buildPackage (commonArgs
    // {
      pname = "food4u-server";
      cargoExtraArgs = "-p food4u-server";
      # Hand the compiled Elm bundle to the crate build; build.rs forwards
      # it to the `rust_embed` `Frontend` type, which bakes the assets into
      # the binary.  Referencing the derivation here also makes it a build
      # dependency, so the Elm bundle is compiled before the crate build.
      RUST_TEMPLATE_FRONTEND_DIR = "${elmFrontend}";
    })
